// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDun9NBd78XsEyObqMz1vrQ-2M6gM31p8c',
    appId: '1:757553481595:web:2d80bbc0c99bbb53899fde',
    messagingSenderId: '757553481595',
    projectId: 'comesolo-uacm',
    authDomain: 'comesolo-uacm.firebaseapp.com',
    storageBucket: 'comesolo-uacm.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTuO3fEn5T_KrEkz0nYTALiV_OrklUGHs',
    appId: '1:757553481595:android:08d6f23de9600f86899fde',
    messagingSenderId: '757553481595',
    projectId: 'comesolo-uacm',
    storageBucket: 'comesolo-uacm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgTj52pR3lf8LkmwZKwbAbZbEAp8Ma5cY',
    appId: '1:757553481595:ios:e565bf89fdbd8531899fde',
    messagingSenderId: '757553481595',
    projectId: 'comesolo-uacm',
    storageBucket: 'comesolo-uacm.firebasestorage.app',
    iosBundleId: 'com.example.comesoloFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgTj52pR3lf8LkmwZKwbAbZbEAp8Ma5cY',
    appId: '1:757553481595:ios:e565bf89fdbd8531899fde',
    messagingSenderId: '757553481595',
    projectId: 'comesolo-uacm',
    storageBucket: 'comesolo-uacm.firebasestorage.app',
    iosBundleId: 'com.example.comesoloFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDun9NBd78XsEyObqMz1vrQ-2M6gM31p8c',
    appId: '1:757553481595:web:8375e099c96da95a899fde',
    messagingSenderId: '757553481595',
    projectId: 'comesolo-uacm',
    authDomain: 'comesolo-uacm.firebaseapp.com',
    storageBucket: 'comesolo-uacm.firebasestorage.app',
  );
}
